#!/usr/bin/env node

// Copyright (c) 2013 Alejandro Blanco <alejandro.b.e@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
// COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
// IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

/*jslint vars: false, node: true, nomen: true */
/*global */

"use strict";

var program = require("commander"),
    fs = require("fs"),
    zlib = require("zlib"),
    string,
    list,
    decipher,
    secrets;

// FUNCTIONS

string = function (val) {
    return String(val);
};

list = function (secrets) {
    var i;
    for (i = 0; i < secrets.length; i += 1) {
        console.log("[" + i + "] " + secrets[i].service);
    }
};

decipher = function (secrets) {};

// MAIN

program
    .version("0.0.0")
    .usage("[options] <backup file>")
    .option("-l, --list", "List passwords")
    .option("-d, --decipher <service>", "Decipher a secret", string)
    .parse(process.argv);

if (program.args.length !== 1) {
    console.log("Wrong number of arguments");
    console.log("Usage: " + program._usage);
    return;
}

try {
    secrets = fs.readFileSync(program.args[0]);
    secrets = zlib.unzip(secrets, function (err, buffer) {
        var secrets = JSON.parse(buffer.toString());

        if (err) {
            console.log(err);
            return;
        }

        if (program.list) {
            list(secrets);
        }

        if (program.decipher) {
            decipher(secrets);
        }
    });
} catch (err) {
    console.log("An error was encountered reading the file: " + program.args[0]);
    console.log(err.message);
}
